databases:
  - name: no_more_db
    databaseName: no_more_db_c1up
    user: no_more_db_c1up_user
    region: Oregon

services:
  - type: web
    name: no_more_db
    env: ruby
    region: Oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    preDeployCommand: ./bin/rails db:migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: no_more_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2